# For changes in dependencies
'📦 dependencies':
  - changed-files:
      - 'package.json'

# For changes in documentation
'📖 documentation':
  - changed-files:
      - 'README.md'

# For changes in source code
'✨ enhancement':
  - changed-files:
      - 'src/*'
      - 'lib/*'

# For changes in site
'🌍 site':
  - changed-files:
      - 'public/*'
