name: Feature Request
description: Share with us your ideas on how Wences could be improved upon.
labels: ['✨ enhancement']
body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: Try to describe in detail the feature you wish existed.
          placeholder: e.g. I want to add X because Y to Z.
      validations:
          required: true
    - type: textarea
      id: use-cases
      attributes:
          label: Use cases
          description: Why do you need this feature? Provide real-life use cases as to why this feature will be useful for others.
          placeholder: e.g. Sometimes, Z is making X and Y is helpful for this scenario.
      validations:
          required: true
    - type: checkboxes
      id: checklist
      attributes:
          label: Checklist
          description: Please check the following items before submitting your issue.
          options:
              - label: I have searched the existing issues to make sure this bug has not already been reported.
                required: true
      validations:
          required: true
